Check if jq is present

diff --git a/.github/workflows/pr-format.yml b/.github/workflows/pr-format.yml
--- a/.github/workflows/pr-format.yml
+++ b/.github/workflows/pr-format.yml
@@ -8,6 +8,7 @@ jobs:
     name: Validate PR Title
     steps:
       - run: |
+          if ! command -v jq; then echo "jq not found" && exit 1; fi
           shopt -s nocasematch
           PR_TITLE="$(jq -r '.pull_request.title' ${{ github.event_path }})"
           if [[ ! $PR_TITLE =~ ^(feat|fix|docs|refactor|ci|test|chore|style|build):\s.*$ ]]; then
